#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/roma
#    username: root
#    password: 1234


spring:
  sql:
    init:
      mode: always
      platform: mariadb
      encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
  datasource:
    url: jdbc:mariadb://localhost:3306/roma
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver